/*
 * TestSuite.java
 * JUnit based test
 *
 * Created on March 22, 2005, 1:28 PM
 */

package se.arexis.agdb.test;

import junit.framework.*;

/**
 *
 * @author heto
 */
public class TestSuite extends TestCase {
    
    public TestSuite(String testName) {
        super(testName);
    }

    protected void setUp() throws java.lang.Exception {
    }

    protected void tearDown() throws java.lang.Exception {
    }

    /**
     * suite method automatically generated by JUnit module
     */
    public static junit.framework.Test suite() {
        junit.framework.TestSuite suite = new junit.framework.TestSuite("TestSuite");
        suite.addTest(se.arexis.agdb.test.testTest.suite());
        suite.addTest(se.arexis.agdb.test.testImportProcessTest.suite());
        return suite;
    }
    
    // TODO add test methods here. The name must begin with 'test'. For example:
    // public void testHello() {}
    
}
